services:
  - type: static
    name: kalogram-frontend
    buildCommand: ./build.sh
    publishDir: build
    staticPublishPath: /
    pullRequestPreviewsEnabled: true
    buildFilter:
      paths:
        - src/**
        - public/**
        - package.json
        - package-lock.json
        - build.sh
    envVars:
      - key: NODE_VERSION
        value: 20.11.1
      - key: NODE_ENV
        value: production
      - key: CI
        value: false
    headers:
      - source: /**
        headers:
          - key: Cache-Control
            value: no-cache
    routes:
      - type: rewrite
        source: /**
        destination: /index.html 