services:
  - type: static
    name: kalogram-frontend
    buildCommand: npm install && npm run build
    publishDir: build
    envVars:
      - key: NODE_VERSION
        value: 18
      - key: NODE_ENV
        value: production
    routes:
      - type: rewrite
        source: /*
        destination: /index.html 