services:
  - type: static
    name: kalogram-frontend
    buildCommand: npm ci && npm run build
    publishDir: build
    staticPublishPath: /
    envVars:
      - key: NODE_VERSION
        value: 20.11.1
      - key: NODE_ENV
        value: production
      - key: CI
        value: false
    headers:
      - source: /**
        headers:
          - key: Cache-Control
            value: no-cache
    routes:
      - type: rewrite
        source: /**
        destination: /index.html 