services:
  - type: static
    name: kalogram-frontend
    buildCommand: npm install && npm run build
    publishDir: build
    staticPublishPath: /
    headers:
      - source: /**
        headers:
          - key: Cache-Control
            value: no-cache
    routes:
      - type: rewrite
        source: /**
        destination: /index.html 